/**
 * dsh-ask-chime — a notification sound for the moment the harness needs a human.
 *
 * Three moments matter, and each is a host-plane seam:
 *
 *  1. A question. The model-facing `ask_user_question` tool and the plan review
 *     (`exit_plan_mode`) both funnel through exactly one method —
 *     `ctx.userQuestions.ask()` — so wrapping that single method covers every
 *     prompt the harness can raise today, and any future tool that asks through
 *     the same channel. The wrapper only fires the sound and then delegates, so
 *     the question itself is passed through untouched.
 *  2. An approval. `approval/request` is a waterfall dispatched only when the
 *     session's policy actually reaches out to a human, so it stays silent for a
 *     call the policy auto-denies.
 *  3. A finished turn. `agent/status` flips `running` → `idle` exactly when an
 *     agent stops working — the same signal the web UI uses to decide whether a
 *     session is busy — so it means "the work stopped", not "the reply ended".
 *     Only root agents chime: a subagent settling mid-task is not your turn
 *     finishing.
 *
 * The sound is played by the operating system's own player, through
 * `node:child_process` — deliberately not through the harness shell service.
 * That service confines every execution with the deployment's sandbox policy,
 * and a confined process spawn for an *agentless* plugin call cannot be assumed
 * to work: measured on Windows 11 with the default `workspace-write` policy,
 * even `echo hello` exits 1 with no output, while the same command under an
 * explicit policy plays fine. The command built here is fixed, takes no input
 * from the model or the session, and does nothing but make a sound.
 *
 * Failure is always contained: a missing player, a muted machine, or a broken
 * sound file can never break the question or the approval it announced.
 *
 * @module dsh-ask-chime
 */
import { execFile } from 'node:child_process'

/** Cordis plugin name, as it appears in the composition tree. */
export const name = 'ask-chime'

/**
 * Hard dependency: the questions seam. Declaring it parks this plugin until the
 * service is live, so the wrapper is never installed into a missing service.
 */
export const inject = ['userQuestions']

/** Default system sounds per platform. Overridable per alert kind via config. */
const SOUNDS = {
  win32: { question: 'chimes.wav', approval: 'Windows Notify Calendar.wav', done: 'Windows Print complete.wav' },
  darwin: { question: 'Glass.aiff', approval: 'Ping.aiff', done: 'Hero.aiff' },
  linux: { question: 'dialog-question.oga', approval: 'message.oga', done: 'complete.oga' },
}

/**
 * The Windows tone tail, in [frequency Hz, duration ms] pairs. Each alert gets
 * its own shape so all three are distinguishable by ear alone: a question
 * falls, an approval rises, and a finished turn climbs a three-note arpeggio.
 * The tail exists because a scheme sound file can be quiet or missing on a
 * given machine while these tones are generated by the OS itself onto the
 * default output device regardless.
 */
const TONES = {
  question: [[1046, 150], [784, 320]],
  approval: [[784, 150], [1046, 320]],
  done: [[784, 150], [988, 150], [1319, 320]],
}

/** The three alert kinds, and the config field that overrides each sound. */
const SOUND_KEYS = { question: 'questionSound', approval: 'approvalSound', done: 'completedSound' }

/** Anything unrecognized falls back to the question alert. */
function normalizeAlert(kind) {
  return kind === 'approval' || kind === 'done' ? kind : 'question'
}

/** Where a bare (non-absolute) sound-file name is looked up, per platform. */
const SOUND_DIRS = {
  darwin: ['/System/Library/Sounds'],
  linux: ['/usr/share/sounds/freedesktop/stereo', '/usr/share/sounds/gnome/default/alerts'],
}

/** Players tried in order on Linux; the first one that exists wins. */
const LINUX_PLAYERS = ['paplay', 'pw-play', 'aplay']

/** Spawn deadline: generous enough for a blocking wav play, short enough to die. */
const SPAWN_TIMEOUT_MS = 20000

/** Single-quote a value for a PowerShell literal (embedded quotes are doubled). */
function psQuote(value) {
  return "'" + String(value).split("'").join("''") + "'"
}

/** Normalize the plugin config: every field is optional, none may throw. */
export function resolveOptions(config) {
  const raw = config === null || typeof config !== 'object' ? {} : config
  const sound = (value) => (typeof value === 'string' && value.length > 0 ? value : null)
  const duration = (value) => (typeof value === 'number' && Number.isFinite(value) && value > 0 ? value : 0)
  return {
    enabled: raw.enabled !== false,
    questions: raw.questions !== false,
    approvals: raw.approvals !== false,
    completed: raw.completed !== false,
    tones: raw.tones !== false,
    questionSound: sound(raw.questionSound),
    approvalSound: sound(raw.approvalSound),
    completedSound: sound(raw.completedSound),
    // 0 disables the gate entirely: every finished turn chimes.
    minTurnMs: duration(raw.minTurnMs),
  }
}

/** The configured sound for one alert, else the platform default, else Linux's. */
function soundFor(alert, platform, options) {
  const override = options[SOUND_KEYS[alert]]
  if (typeof override === 'string' && override.length > 0) return override
  const table = SOUNDS[platform] === undefined ? SOUNDS.linux : SOUNDS[platform]
  return table[alert]
}

/** The PowerShell statement sequence that plays a wav, then the tone tail. */
function windowsScript(kind, file, options) {
  const statements = [
    "$ErrorActionPreference='SilentlyContinue'",
    '$ok=$false',
    'try{'
      + '$p=' + psQuote(file) + ';'
      + 'if(-not [System.IO.Path]::IsPathRooted($p)){$p=Join-Path (Join-Path $env:WINDIR ' + psQuote('Media') + ') $p};'
      + '$w=New-Object System.Media.SoundPlayer $p;$w.PlaySync();$ok=$true'
      + '}catch{}',
  ]
  // `!== false`, not truthiness: `buildCommands` is public and may be handed a
  // partial options object that never went through `resolveOptions`, where an
  // absent `tones` means "default on".
  if (options.tones !== false) {
    const pairs = TONES[normalizeAlert(kind)]
    const tones = pairs
      .map((pair, index) => (index === 0 ? '' : 'Start-Sleep -Milliseconds 80;') + '[console]::beep(' + pair[0] + ',' + pair[1] + ')')
      .join(';')
    statements.push('try{' + tones + ';$ok=$true}catch{}')
  }
  // Last resort: the sound scheme's own notification alias. Silent under a
  // scheme that maps it to nothing, which is why it is not the first choice.
  statements.push('if(-not $ok){try{[System.Media.SystemSounds]::Asterisk.Play();Start-Sleep -Milliseconds 1200;$ok=$true}catch{}}')
  // Report the outcome so the caller can fall through to the next candidate
  // instead of trusting an exit code that a swallowed error would fake.
  statements.push('if($ok){exit 0}else{exit 1}')
  const script = statements.join(';')
  // powershell.exe ships with every supported Windows and needs no console for
  // either branch (measured: wav playback and `[console]::beep` both succeed
  // under a hidden, console-less spawn). pwsh is tried second for the machines
  // that ship PowerShell 7 instead; it is not guaranteed to be on PATH.
  return [
    { file: 'powershell.exe', args: ['-NoLogo', '-NoProfile', '-NonInteractive', '-Command', script] },
    { file: 'pwsh.exe', args: ['-NoLogo', '-NoProfile', '-NonInteractive', '-Command', script] },
  ]
}

/** Every candidate command for one alert, in the order they should be tried. */
export function buildCommands(kind, options = {}) {
  const platform = typeof options.platform === 'string' ? options.platform : process.platform
  const alert = normalizeAlert(kind)
  const file = soundFor(alert, platform, options)

  if (platform === 'win32') return windowsScript(alert, file, options)

  if (platform === 'darwin') {
    const path = file.startsWith('/') ? file : SOUND_DIRS.darwin[0] + '/' + file
    return [{ file: 'afplay', args: [path] }]
  }

  const paths = file.startsWith('/') ? [file] : SOUND_DIRS.linux.map((dir) => dir + '/' + file)
  const commands = []
  for (const path of paths) {
    for (const player of LINUX_PLAYERS) commands.push({ file: player, args: [path] })
  }
  return commands
}

/** Spawn one candidate and report its failure message, or null when it worked. */
function runOne(spawn, command) {
  return new Promise((resolve) => {
    try {
      spawn(command, (error) => {
        resolve(error === null || error === undefined ? null : String(error.message === undefined ? error : error.message))
      })
    } catch (error) {
      resolve(String(error && error.message !== undefined ? error.message : error))
    }
  })
}

/** The default spawner: no console window, bounded lifetime, output discarded. */
function defaultSpawn(command, done) {
  execFile(command.file, command.args, { windowsHide: true, timeout: SPAWN_TIMEOUT_MS }, (error) => done(error === undefined ? null : error))
}

/**
 * Play one alert, trying each candidate command until one spawns.
 *
 * @param kind - `'question'`, `'approval'`, or `'done'`.
 * @param options - resolved options plus an optional `platform` override.
 * @param spawn - test seam: `(command, done) => void`, defaulting to `execFile`.
 * @returns `null` when a player ran, else the failure messages that were tried.
 */
export async function playAlert(kind, options = {}, spawn = defaultSpawn) {
  const failures = []
  for (const command of buildCommands(kind, options)) {
    const failure = await runOne(spawn, command)
    if (failure === null) return null
    failures.push(command.file + ': ' + failure)
  }
  return failures
}

function describe(error) {
  return String(error && error.message !== undefined ? error.message : error)
}

/**
 * Install the three hooks. Exported so tests can drive the exact wiring with a
 * fake context and a fake player.
 *
 * @param ctx - a cordis context (the real one, or a test double).
 * @param options - resolved options from {@link resolveOptions}.
 * @param play - test seam replacing {@link playAlert}; may return a promise.
 */
export function install(ctx, options, play) {
  const fire = (kind) => {
    try {
      const result = play === undefined
        ? playAlert(kind, { ...options, platform: process.platform })
        : play(kind)
      if (result !== null && typeof result === 'object' && typeof result.then === 'function') {
        result.then(
          (failures) => {
            if (failures !== null && failures !== undefined) {
              console.warn('[ask-chime] could not play the ' + kind + ' alert: ' + failures.join('; '))
            }
          },
          (error) => console.warn('[ask-chime] ' + kind + ' alert failed: ' + describe(error)),
        )
      }
    } catch (error) {
      console.warn('[ask-chime] ' + kind + ' alert failed: ' + describe(error))
    }
  }

  if (options.questions) {
    const questions = ctx.get('userQuestions')
    if (questions === undefined || typeof questions.ask !== 'function') {
      console.warn('[ask-chime] userQuestions.ask is unavailable: the question chime is not armed')
    } else if (questions.ask.__askChime === true) {
      console.warn('[ask-chime] the question chime is already armed')
    } else {
      const original = questions.ask
      const chime = function askWithChime(request) {
        fire('question')
        return original.call(questions, request)
      }
      chime.__askChime = true
      questions.ask = chime
      // Restore the prototype method, but never clobber whoever wrapped after us.
      ctx.effect(() => () => {
        if (questions.ask === chime) delete questions.ask
      })
    }
  }

  if (options.approvals) {
    ctx.on('approval/request', (request, next) => {
      fire('approval')
      return next()
    })
  }

  if (options.completed) {
    // The agent registry is only needed to tell a root agent from a subagent, so
    // it is read optionally: without it every agent chimes, which is noisy but
    // never silent.
    const agents = ctx.get('agents')
    const startedAt = new Map()
    ctx.on('agent/status', (payload) => {
      try {
        if (payload === null || typeof payload !== 'object') return
        const agent = payload.agent
        if (agent === null || agent === undefined) return
        if (payload.status === 'running') {
          startedAt.set(agent.id, Date.now())
          return
        }
        if (payload.status !== 'idle') return
        const began = startedAt.get(agent.id)
        startedAt.delete(agent.id)
        if (agents !== undefined && !agents.roots().includes(agent)) return
        if (options.minTurnMs > 0 && began !== undefined && Date.now() - began < options.minTurnMs) return
        fire('done')
      } catch (error) {
        // Observation must never break the dispatch it is watching.
        console.warn('[ask-chime] status listener failed: ' + describe(error))
      }
    })
  }
}

/**
 * Cordis plugin entry.
 *
 * @param ctx - the host context this row was loaded into.
 * @param config - the row's `config:` block; every field is optional.
 */
export function apply(ctx, config) {
  const options = resolveOptions(config)
  if (!options.enabled) {
    console.warn('[ask-chime] disabled by config; no chime will play')
    return
  }
  install(ctx, options)
}
